name: Deploy Front Production

on:
  push:
    branches: 
      - 'main'
env:
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ROLE_SESSION_NAME: ${{ secrets.AWS_ROLE_SESSION_NAME }}

permissions:
    id-token: write
    contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_SESSION_NAME }}
          role-session-name: "GitHubActions"
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run a multi-line script
        run: |
          yarn
          yarn build

      - name: Upload to S3
        run: aws s3 sync ./build s3://${{ env.BUCKET_NAME }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
